import type { CSSProperties } from 'react';
import { BASE_URL } from '../env';

/** Small owned icons (inline SVG) so primary UI never depends on platform emoji. */
export function BrickIcon({ size = 28, color = '#E63946', style }: { size?: number; color?: string; style?: CSSProperties }) {
  return (
    <svg aria-hidden width={size} height={size * 0.75} viewBox="0 0 40 30" style={{ flex: '0 0 auto', ...style }}>
      <rect x="2" y="10" width="36" height="18" rx="4" fill={color} stroke="#1D2A44" strokeWidth="2.5" />
      <rect x="7" y="3" width="9" height="8" rx="2" fill={color} stroke="#1D2A44" strokeWidth="2.2" />
      <rect x="24" y="3" width="9" height="8" rx="2" fill={color} stroke="#1D2A44" strokeWidth="2.2" />
      <path d="M7 16 Q10 13.5 15 14" stroke="#fff" strokeWidth="2" strokeLinecap="round" fill="none" opacity=".7" />
    </svg>
  );
}

export function LockIcon({ size = 24, style }: { size?: number; style?: CSSProperties }) {
  return (
    <svg aria-hidden width={size} height={size} viewBox="0 0 24 24" style={{ flex: '0 0 auto', ...style }}>
      <path d="M7 11V8a5 5 0 0 1 10 0v3" fill="none" stroke="#1D2A44" strokeWidth="2.6" strokeLinecap="round" />
      <rect x="4" y="10.5" width="16" height="11" rx="3" fill="#FFD60A" stroke="#1D2A44" strokeWidth="2.2" />
      <circle cx="12" cy="16" r="1.8" fill="#1D2A44" />
    </svg>
  );
}

export function CheckIcon({ size = 24, style }: { size?: number; style?: CSSProperties }) {
  return (
    <svg aria-hidden width={size} height={size} viewBox="0 0 24 24" style={{ flex: '0 0 auto', ...style }}>
      <circle cx="12" cy="12" r="10.5" fill="#7AE582" stroke="#1D2A44" strokeWidth="2.2" />
      <path d="M6.8 12.6l3.6 3.6 6.8-7.4" fill="none" stroke="#1D2A44" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

/** URL of a custom sticker icon from public/art/icons (generated by `npm run icons:generate`). */
export const iconUrl = (id: string): string => `${BASE_URL}art/icons/${id}.webp`;

/** Decorative sticker icon. `size` is any CSS length (e.g. f(40)); pass a `label` only if it is the sole content. */
export function Icon({ id, size = 28, style, label, gap }: { id: string; size?: number | string; style?: CSSProperties; label?: string; gap?: number | string }) {
  return (
    <img
      src={iconUrl(id)}
      alt={label ?? ''}
      draggable={false}
      style={{ width: size, height: size, objectFit: 'contain', flex: '0 0 auto', display: 'inline-block', verticalAlign: 'middle', pointerEvents: 'none', marginRight: gap, ...style }}
    />
  );
}

/** Chunky navy chevron (owned SVG, so it never renders as a platform emoji like U+25B6 can on iOS). */
export function ChevronIcon({ dir = 'right', size = 22, style }: { dir?: 'left' | 'right'; size?: number | string; style?: CSSProperties }) {
  return (
    <svg aria-hidden width={size} height={size} viewBox="0 0 24 24" style={{ flex: '0 0 auto', verticalAlign: 'middle', transform: dir === 'left' ? 'scaleX(-1)' : undefined, ...style }}>
      <path d="M8 4.5l8.5 7.5L8 19.5" fill="none" stroke="currentColor" strokeWidth="4.2" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}
