/**
 * Story templates. Slots: {hero} {they} {them} {their} {place} {atPlace} {problem} {power}.
 * Rules: past tense only after {they} (no "they is/was"), {problem} and {power} are noun phrases used
 * as objects, no villains, everything ends happy. Sentence-initial letters are capitalised by the generator.
 */
export const templates: string[][] = [
  [
    'One sunny morning, {hero} was sipping a chai latte {atPlace}.',
    'Suddenly, {they} spotted {problem}!',
    '{hero} grinned, because {they} had {power}.',
    'ZAP! Everything was fixed, and everybody cheered for more chai lattes.',
  ],
  [
    '{hero} went to {place} with a basket of orange chicken.',
    'But oh my, {they} bumped into {problem}!',
    'Quick as a wink, {hero} used {power}.',
    'Soon the problem was gone, and the orange chicken tasted extra yummy.',
  ],
  [
    'It was tea time {atPlace}, and {hero} had the fanciest teacup of all.',
    'Then {they} noticed {problem}, looking a little lost.',
    '"No worries," said {hero}, pulling out {power}.',
    'Everything turned out wonderful, and tea time was saved. Cheers!',
  ],
  [
    'Once upon a Tuesday, {hero} played a tiny tennis match {atPlace}.',
    'Plop! Out of nowhere came {problem}.',
    '{hero} winked and used {power}, because {they} always had a plan.',
    'Everybody clapped, and the game ended with a hug for every player.',
  ],
  [
    '{hero} loved visiting {place}, especially when there was a drum solo.',
    'Today, though, {they} found {problem}.',
    'With {power} in {their} hands, {hero} gave it a big, friendly try.',
    'It worked so well that the whole sky did a happy wiggle.',
  ],
  [
    'Everybody knew that {hero} was the best at making cozy plans {atPlace}.',
    'So when {problem} showed up, {they} did not panic one bit.',
    '{hero} took a deep breath and used {power}.',
    'Just like that, all was calm, cozy, and a little bit sparkly.',
  ],
  [
    'Plink, plonk! The morning began with a piano tune {atPlace}.',
    '{hero} tiptoed closer and discovered {problem}.',
    '"I know just what to do!" {they} said, and used {power}.',
    'The tune turned into a giggly song, and everybody danced along.',
  ],
  [
    'The day {hero} went to {place}, even the clouds were smiling.',
    'Then came {problem}, and the smiles got a little wobbly.',
    'Luckily, {hero} had {power}, and wow, did it work!',
    'By sunset, the clouds were giggling again, and so was {hero}.',
  ],
  [
    '{hero} packed a snack and set off for {place}.',
    'Halfway there, {they} met {problem}.',
    '"Hmm," thought {hero}. "Time for {power}!"',
    'A swirl of sparkles later, a new friendship began, and there was a snack to share.',
  ],
  [
    'A very silly breeze blew through {place} one afternoon.',
    '{hero} looked up and saw {problem} floating by.',
    'Out came {power}, and {hero} gave a little bow.',
    'The breeze laughed, the trouble melted away, and it was the best afternoon ever.',
  ],
  [
    'In a land of bricks and bubbles, {hero} was the kindest explorer.',
    'One day {they} came across {problem} {atPlace}.',
    '{hero} did not run away. Instead, {they} reached for {power}.',
    'The land sparkled, and everybody agreed that kindness is the strongest magic.',
  ],
  [
    '{hero} was practicing piano and drums {atPlace} when something strange happened.',
    'There it was: {problem}!',
    'Boom, tap, ding! {hero} used {power} to the beat.',
    'The beat was so good that even the trees clapped along.',
  ],
  [
    'It was a quiet evening {atPlace}, and {hero} was telling a bedtime story.',
    'In the middle of the story, in strolled {problem}.',
    '{hero} smiled and gently used {power}.',
    'Then everyone yawned, snuggled up, and had the sweetest dreams.',
  ],
  [
    '{hero} made a wish for a Yorkshire terrier puppy, and the wish floated off {atPlace}.',
    'Instead of a puppy, the wish brought {problem}!',
    '{hero} laughed, grabbed {power}, and got to work.',
    'In the end, a tiny, fluffy cloud shaped like a puppy waved goodbye. What a day!',
  ],
  [
    'Three, two, one, giggle! {hero} began the day with a happy hop {atPlace}.',
    'Nobody expected {problem}, not even {hero}.',
    'No problem, because {they} had {power}.',
    'One big poof, and the day went back to being wonderfully silly.',
  ],
  [
    'The broccoli jokes were flying {atPlace}, and {hero} was laughing the loudest.',
    'Then {they} saw {problem}, and the laughing stopped for one second.',
    '{hero} lifted {power} high and shouted, "Hooray for helping!"',
    'The jokes started up again, and the broccoli even got a little hug. Aww!',
  ],
  [
    'Deep in the sparkly morning, {hero} wandered through {place}.',
    '"What is that?" {they} wondered, staring at {problem}.',
    'With a twirl and {power}, the answer popped out like a bubble.',
    'And the answer was: more fun! So everybody played until the stars came out.',
  ],
  [
    '{hero} dressed up in the sparkliest outfit and went to {place}.',
    'Every sparkle shimmered, until {they} spotted {problem}.',
    'Nothing could stop {hero}, not with {power} in {their} pocket!',
    'The sparkles got even brighter, and so did {their} smile.',
  ],
  [
    'Jingle Bells jingled, Rudolph woofed, and {hero} stepped out {atPlace}.',
    'A surprise was waiting there: {problem}!',
    '{hero} thought hard, then used {power}.',
    'The surprise turned into a party, and the whole family joined in.',
  ],
  [
    'Magic was in the air {atPlace}, and {hero} could feel it in {their} toes.',
    '{they} tiptoed forward and found {problem}.',
    '"Time for something special," said {hero}, using {power}.',
    'Sparkles filled the air, and everyone said, "Wow!"',
  ],
  [
    'A little tune from the Rudolph song floated by {place}.',
    '{hero} hummed along until {they} noticed {problem}.',
    'So {hero} brought out {power} and sang even louder.',
    'The whole place joined the chorus, and it was the merriest day of the year.',
  ],
  [
    '{hero} had a very important job {atPlace}: to keep the chai latte warm.',
    'But along came {problem}, and the job got interesting.',
    '{hero} used {power} and did a little victory dance.',
    'The chai latte stayed warm, and everybody got a sip. Slurp!',
  ],
  [
    'Every Saturday, {hero} visited {place} to see what funny things were there.',
    'This Saturday, there was {problem}!',
    '{hero} chuckled, then used {power} with a wiggle.',
    'The funny thing got even funnier, and everybody laughed until they hiccupped.',
  ],
  [
    'Near {place}, a small, shiny door appeared in the grass.',
    '{hero} peeked in and met {problem}.',
    '"Come on out," said {hero}, and used {power}.',
    'Out came the biggest, happiest cheer, and the door sparkled shut.',
  ],
  [
    'It was a bright, bouncy day, and {hero} was ready for anything.',
    'First stop: {place}. Second stop: {problem}!',
    'Using {power}, {hero} turned the tricky bit into a trick bit, and a very good one.',
    'Then came a victory snack, and the best part was sharing it.',
  ],
  [
    '{hero} found a map with a big pink star on {place}.',
    'Following the map, {they} met {problem}.',
    'The map said, "Use {power}." So {hero} did!',
    'Treasure! It was a pile of bricks, a pile of cookies, and a very big hug.',
  ],
  [
    'The stars blinked hello {atPlace}, and {hero} blinked right back.',
    'A little later, {they} found {problem} in a very odd spot.',
    '{hero} fetched {power} and made a wish.',
    'The wish came true: everything was fixed, and the stars did a happy twinkle.',
  ],
  [
    'Brrring! The tea-time bell rang {atPlace}.',
    '{hero} hurried over, but bumped into {problem} on the way.',
    'Out of {their} pocket came {power}, ready to save the day.',
    'Tea time started right on time, with extra cookies as a prize.',
  ],
  [
    '{hero} had been waiting all week to visit {place}.',
    'When {they} arrived, there was {problem}!',
    '"Wow!" said {hero}. "This will be great for my story."',
    'So {they} used {power}, and the story became the best one anyone had ever heard.',
  ],
  [
    'Once, in a place made of bricks, {hero} built a very tall tower {atPlace}.',
    'Up at the top, {they} found {problem}, waiting politely.',
    '"Let me help," said {hero}, and used {power}.',
    'Down the tower slid a rainbow, and everyone took a turn riding it.',
  ],
  [
    'Today, {hero} was in charge of the giggles {atPlace}.',
    'But {problem} was messing up the giggle schedule!',
    '{hero} stayed calm and used {power}.',
    'The giggle schedule was fixed, and the giggles came out better than ever.',
  ],
  [
    'Whoosh! A warm wind carried {hero} all the way to {place}.',
    'There, {they} met {problem}, who needed a friend.',
    '{hero} offered a cookie and used {power}.',
    'The new friend giggled, and the two of them played until bedtime.',
  ],
  [
    'Tippy-tap! {hero} danced a little jig {atPlace}.',
    'The dance woke up {problem}, who did not mind one bit.',
    'To say thanks, {hero} used {power} and made a rainbow bridge.',
    'Everybody crossed the bridge, singing and skipping the whole way.',
  ],
  [
    '{hero} stirred a pot of something delicious {atPlace}.',
    'It smelled so good that {problem} came to say hello.',
    'Together with {power}, {hero} made a feast for all.',
    'Everybody had seconds, and there was even a bowl for the broccoli. A very small bowl.',
  ],
  [
    'Rudolph howled a happy song, and {hero} sang along {atPlace}.',
    'Then, from behind a tree, popped out {problem}.',
    '"Surprise!" laughed {hero}, and used {power}.',
    'The surprise turned into a dance party, and the moon came to watch.',
  ],
  [
    'When the sun yawned, {hero} woke up {atPlace} and stretched.',
    '{they} rubbed {their} eyes and gasped at {problem}.',
    'Smart as ever, {hero} used {power} and a big smile.',
    'Breakfast was served, pancakes for everybody, and the day got off to a lovely start.',
  ],
  [
    'Ready, set, wiggle! {hero} began a game of hide-and-seek {atPlace}.',
    'Behind a bush hid {problem}, giggling quietly.',
    'Found you! {hero} used {power} to say hello.',
    'Everybody laughed, and the next round of hide-and-seek began.',
  ],
  [
    'A sparkly note arrived for {hero}: "Please come to {place}!"',
    'When {they} got there, {they} saw {problem} and a very worried-looking sky.',
    '{hero} did not worry, because {they} had {power}.',
    'Poof! The sky giggled, and the sparkly note said, "Thank you!"',
  ],
  [
    'At {place}, {hero} did something nobody had done before: a cartwheel while holding a teacup.',
    'It did not spill a single drop, and out popped {problem} to see it.',
    '"Can you do it too?" asked {hero}, and used {power}.',
    'Everyone tried a cartwheel, and there was a giant pile of giggles.',
  ],
  [
    'Wishes, wishes, wishes! {hero} made three wishes {atPlace}.',
    'The first wish was for tea. The second was for sprinkles. The third brought {problem}!',
    '{hero} shrugged and used {power}, because every wish deserved a happy ending.',
    'All the wishes came true, and the sprinkles even went on the tea.',
  ],
  [
    'Happy birthday to the whole world! That was what {hero} thought {atPlace}.',
    'Then {problem} turned up, wearing a tiny party hat.',
    '"Come to the party," said {hero}, using {power} to make confetti.',
    'The party lasted all day, and the cake was big enough for every single guest.',
  ],
];
