// Generates/keeps src/config/passwords.ts (committed) and writes private/coupon-passwords.md.
// Stable across runs unless --new-passwords. Run: npm run passwords [-- --new-passwords]
import fs from 'node:fs';
import path from 'node:path';
import { coupons } from '../../src/config/coupons';
import { COUPON_IDS } from '../../src/types';
import { passwords as existing } from '../../src/config/passwords';
import { generatePasswords } from './passwords';

const CONFIG = path.resolve('src/config/passwords.ts');
const renew = process.argv.includes('--new-passwords');
const passwords = generatePasswords(COUPON_IDS, existing, { renew });

const body = COUPON_IDS.map((id) => `  ${id}: '${passwords[id]}',`).join('\n');
fs.writeFileSync(
  CONFIG,
  `import type { CouponId } from '../types';\n\n/** Coupon passwords shown on the coupon card. Generated by \`npm run passwords\`; stable unless --new-passwords. */\nexport const passwords: Record<CouponId, string> = {\n${body}\n};\n`,
);

const rows = coupons.map((c) => `| ${c.title} | ${c.zone} | \`${passwords[c.id]}\` |`);
fs.mkdirSync('private', { recursive: true });
fs.writeFileSync('private/coupon-passwords.md', ['# Coupon passwords', '', '| Coupon | Zone | Password |', '| --- | --- | --- |', ...rows, ''].join('\n'));
console.log(`${renew ? 'Regenerated' : 'Kept/filled'} passwords in src/config/passwords.ts and private/coupon-passwords.md`);
