import type { SpeakerId } from './voices';
import { welcomeMessage } from './family';

export interface CopyLine {
  speaker: SpeakerId;
  text: string;
}

/**
 * Spoken lines for the global flow (title, hub, dig, coupon, brick, finale).
 * Every string here is pre-generated by `npm run voices:extract` + `voices:generate`.
 * Speak them with say(COPY.x, { speaker: 'narrator' }). Keep them warm and short.
 */
export const COPY = {
  titleWelcome: 'Happy birthday, Luna! Tap Play to visit your island.',
  hubIntro: 'This is your birthday island! Tap a building to go inside.',
  hubHintStory: 'The Story Tower! Mom has a story to make with you.',
  hubHintScience: 'The Science Lab! Julian is cooking up something fun.',
  hubHintTennis: 'The Tennis Court! Darian wants to play with you.',
  hubHintMusic: 'The Music Stage! Daddy is tuning his guitar.',
  hubHintWoods: 'The Whispering Woods! Rudolph and Jingle Bells are waiting.',
  hubHintCloset: 'The closet! Pick something sparkly to wear.',
  hubHintCoupons: 'The coupon box! Your prizes will be kept here.',
  comingSoon: 'Coming soon! That building is still getting built.',
  closetIntro: 'Pick your favorite outfit, Luna!',
  couponBoxIntro: 'Your coupons live here. Find buried treasure to fill the box!',
  couponBoxEmpty: 'No coupons yet. Keep exploring, Luna!',
  digPrompt: 'Something is buried here! Tap to help Rudolph and Jingle Bells dig!',
  digKeepGoing: 'Keep digging! You are so close!',
  couponFound: 'You found a coupon! Show this to Daddy!',
  brickEarned: 'You earned a Birthday Brick!',
  finaleGather: 'You did it, Luna! Let us all gather around the birthday cake!',
  finaleCandles: 'Make a wish, and blow out the candles!',
  finaleFireworks: 'Hooray! Look at the fireworks!',
  finaleAlbum: 'Here are some of our favorite memories with you.',
  finaleEnd: 'Happy birthday, Luna! We love you so much!',
} as const;

/** Flat list consumed by scripts/voices/lines.ts. */
export const copyLines: CopyLine[] = [
  ...Object.values(COPY).map((text) => ({ speaker: 'narrator' as const, text })),
  // Daddy's note on the title screen ("Read it to me")
  { speaker: 'dad', text: welcomeMessage.body },
  { speaker: 'dad', text: welcomeMessage.signoff },
];
