import type { SpeakerId } from './voices';
import { welcomeMessage, finaleMessage } from './family';

export interface CopyLine {
  speaker: SpeakerId;
  text: string;
}

/**
 * Spoken lines for the global flow (title, hub, dig, coupon, brick, finale).
 * Every string here is pre-generated by `npm run voices:extract` + `voices:generate`.
 * Speak them with say(COPY.x, { speaker: 'narrator' }). Keep them warm and short.
 */
export const COPY = {
  titleWelcome: 'Happy birthday, Luna! Tap Play to visit your island.',
  hubIntro: 'This is your birthday island! Tap a building to go inside.',
  hubHintStory: 'The Story Tower! Mom has a story to make with you.',
  hubHintScience: 'The Science Lab! Julian is cooking up something fun.',
  hubHintTennis: 'The Tennis Court! Darian wants to play with you.',
  hubHintMusic: 'The Music Stage! Daddy is tuning his guitar.',
  hubHintWoods: 'The Whispering Woods! Rudolph and Jingle Bells are waiting.',
  hubLegend: "Bricks build the birthday cake. Beat a zone's Coupon Challenge to dig up a Daddy-Daughter Date coupon!",
  hubHintCloset: 'The closet! Pick something sparkly to wear.',
  hubHintCoupons: 'The coupon box! Your prizes will be kept here.',
  comingSoon: 'Coming soon! That building is still getting built.',
  closetIntro: 'Pick your favorite outfit, Luna!',
  couponBoxIntro: 'Your coupons live here. Find buried treasure to fill the box!',
  couponBoxEmpty: 'No coupons yet. Keep exploring, Luna!',
  digPrompt: 'Something is buried here! Tap to help Rudolph and Jingle Bells dig!',
  digKeepGoing: 'Keep digging! You are so close!',
  couponFound: 'You found a coupon! Show this to Daddy!',
  brickEarned: 'You earned a Birthday Brick!',
  finaleGather: 'You did it, Luna! Let us all gather around the birthday cake!',
  finaleCandles: 'Make a wish, and blow out the candles!',
  finaleFireworks: 'Hooray! Look at the fireworks!',
  finaleAlbum: 'Here are some of our favorite memories with you.',
  finaleEnd: 'Happy birthday, Luna! We love you so much!',
} as const;

/** Extra finale lines (the message itself lives in family.ts as finaleMessage). */
export const finale = {
  singAlong: 'Everybody, sing along!',
  cheese: 'Say cheese, everybody!',
} as const;

/** Spoken when Luna taps a locked closet item: how many Birthday Bricks it needs (1-7) and where to earn them. */
export const closetLockedLine = (bricks: number): string =>
  `Earn ${bricks} Birthday ${bricks === 1 ? 'Brick' : 'Bricks'} to wear this! Play in the Story Tower and the Whispering Woods.`;

/** Flat list consumed by scripts/voices/lines.ts. */
export const copyLines: CopyLine[] = [
  ...Object.values(COPY).map((text) => ({ speaker: 'narrator' as const, text })),
  ...[1, 2, 3, 4, 5, 6, 7].map((n) => ({ speaker: 'narrator' as const, text: closetLockedLine(n) })),
  ...Object.values(finale).map((text) => ({ speaker: 'narrator' as const, text })),
  // Mom and Dad's note at the end of the finale ("Read it to me")
  { speaker: 'dad', text: finaleMessage.dad },
  { speaker: 'mom', text: finaleMessage.mom },
  // Daddy's note on the title screen ("Read it to me")
  { speaker: 'dad', text: welcomeMessage.body },
  { speaker: 'dad', text: welcomeMessage.signoff },
];
