import type { CouponId } from '../types';

/** Coupon passwords shown on the coupon card. Generated by `npm run passwords`; stable unless --new-passwords. */
export const passwords: Record<CouponId, string> = {
  movies: 'RIVER-JAZZY-20',
  videogames: 'SHELL-CLOVER-57',
  shopping: 'PANDA-SWAN-78',
  icecream: 'COOKIE-PIXIE-64',
};
